AWSTemplateFormatVersion: 2010-09-09
Description: |
This CloudFormation Template was written for running Kittens Carousel Static Website on EC2. 
Kittens Carousel Static Website will be deployed on Amazon Linux 2 (XXXXXXXXXXXX) EC2 Instance
with custom security group which allows http connections on port 80 and ssh port 22 from anywhere. 
Kittens Carousel Static Website  is downloaded from my Public Github repository, 
then deployed on Apache Web Server.
  
Resources:
  LogicalID:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "String" # Required
      GroupName: "String"
      SecurityGroupEgress: 
        SecurityGroupEgress
      SecurityGroupIngress: 
        SecurityGroupIngress
      Tags: 
        Tags
      VpcId: "String"
  

  
Outputs: